### PR TITLE
[WIP] Add update agent pose functions in example.py

### PR DESCRIPTION
**Pull request by brucecui97**
## Motivation and Context

-To incorporate a kinematic agent model

-To please obtain feedback on how to improve current kinematic agent model implementation

In summary, a good model (e.g. kinematic, dynamic) is needed to make the agent’s motion more realistic. Ultimately, if the model is an accurate representation of the agent in the physical world, we can be confident that if the agent's controller (e.g. PID, MPC) works in the simulated environment, the controller will also work in the real world. 
 
## How Has This Been Tested

Ran example.py

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dhruvbatra** [comment]
Thanks. Can you please label this [WIP]?

**Comment by brucecui97** [comment]
Sorry I might be wrong, but I don't think I have permission to add labels

**Comment by mathfac** [comment]
@brucecui97, thank you for the PR. That's valuable feedback. Can you elaborate more when you need this type of kinematic agent model?

Regarding example, I like how you model more sophisticated dynamics here and showcase the HSIM (Habitat Simulator) and HAPI (Habitat API). We should think, what exactly we want to demonstrate here and maybe create custom Agent/Simulator wrapper that encapsulates that logic.

**Comment by mathfac** [comment]
While this PR is a great example how kinematic can be added to Habitat on high level we have [ native support for the kinematic in the Habitat](https://github.com/facebookresearch/habitat-sim/pull/211).
cc @aclegg3 for example of people's requests.
Closing PR for now, feel free to re-open it if it's relevant.

**Pull request closed without merging**
