### PR TITLE
Build api doc in CI

### PR DESCRIPTION
**Pull request by dhruvbatra**
## Motivation and Context

Addresses: 
https://github.com/facebookresearch/habitat-sim/pull/615#discussion_r422681983

## How Has This Been Tested

Same piece of code as on h-sim CI config.

### CODE REVIEW

**Comment by erikwijmans** [comment]
Hmm, looks like habitat-api documentation building requires habitat-sim docs to be built (which makes sense, they cross link between each other).

Adding 

```bash
pushd ../../habitat-sim

python setup.py install --headless

pushd docs

mkdir -p ../build/docs
./build-public.sh

popd
popd
```

before the current call to `./build-public.sh` for habitat-api should fix.  The rebuild is because we are using python=3.8 for the doc build.

**Comment by dhruvbatra** [comment]
Thanks for catching that. But perhaps it's cleaner to create a separate job for building habitat-sim docs (like in the habitat-sim repository)? So that we disentangle what is causing tests to fail.

**Comment by dhruvbatra** [comment]
How's this?

**Comment by erikwijmans** [comment]
Yeah, that seems better!  Looks like habitat-api's CI isn't setup to install bullet however, so the build with bullet is failing.

**Comment by mosra** [comment]
I don't think it's needed to build the full sim docs here, only download the `objects.inv` file from a previous build. Testing a thing right now, will report back when the CI stops failing for me.

**Comment by mosra** [comment]
Opened a PR to your PR: #396

**Comment by dhruvbatra** [comment]
@mathfac -- this is ready for review and merging.

**Pull request merged**
