### PR TITLE
Local planner

### PR DESCRIPTION
**Pull request by erikwijmans**
## Motivation and Context

Change to using habitat-sim's shortest path follower  -- it is faster and creates better paths when there is no sliding.  The one in https://github.com/facebookresearch/habitat-sim/pull/546 will make this functionality even better and will do much better under noise.

## How Has This Been Tested

It makes paths!  Almost all the testing of this is now in habitat-sim, this is just a compatibility layer.

## Types of changes

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by erikwijmans** [comment]
@mathfac @Skylion007 made this compatible with the current follower in habitat-sim.  I will make sure the new one is compatible with this too.

**Comment by mathfac** [comment]
rebased needed as https://github.com/facebookresearch/habitat-sim/pull/546 was merged.

**Comment by Xiaoming-Zhao** [comment]
> Tested the PR from Habitat-API level. Works great with noisy actions as well!
> Example of navigation:
> Screenshot 2020-04-29 20 43 50
> !

@mathfac Hi, may I know what key I need to specify if I want to utilize noisy shortest path follower?
- From the [definition](https://github.com/facebookresearch/habitat-sim/blob/d3c746894c3aa3f62cc972660597ebedfb8a0761/habitat_sim/nav/greedy_geodesic_follower.py#L12) of `GreedyGeodesicFollower` in Habitat-Sim, I need to input an action key to give a signal that I want to use noisy locobot control
- From the Habitat-API level, it seems like I need to give a `enum` for reach action as [here](https://github.com/facebookresearch/habitat-api/blob/master/habitat/tasks/nav/shortest_path_follower.py#L53)
- Meanwhile, when Habitat-API defines the [noisy action specification](https://github.com/facebookresearch/habitat-api/blob/master/habitat/sims/habitat_simulator/actions.py#L137), it uses the same `enum` as the default `HabitatSimActions`.

I do not have a clear view of how to tell the shortest path follower that I want the noisy configuration. Any suggestion? Thanks a lot

**Comment by Xiaoming-Zhao** [comment]
> > Tested the PR from Habitat-API level. Works great with noisy actions as well!
> > Example of navigation:
> > Screenshot 2020-04-29 20 43 50
> > !
> 
> Hi @mathfac and @erikwijmans, may I know what key I need to specify if I want to utilize noisy shortest path follower?
> 
> * From the [definition](https://github.com/facebookresearch/habitat-sim/blob/d3c746894c3aa3f62cc972660597ebedfb8a0761/habitat_sim/nav/greedy_geodesic_follower.py#L12) of `GreedyGeodesicFollower` in Habitat-Sim, I need to input an action key to give a signal that I want to use noisy locobot control
> * From the Habitat-API level, it seems like I need to give a `enum` for reach action as [here](https://github.com/facebookresearch/habitat-api/blob/master/habitat/tasks/nav/shortest_path_follower.py#L53)
> * Meanwhile, when Habitat-API defines the [noisy action specification](https://github.com/facebookresearch/habitat-api/blob/master/habitat/sims/habitat_simulator/actions.py#L137), it uses the same `enum` as the default `HabitatSimActions`.
> 
> I do not have a clear view of how to tell the shortest path follower that I want the noisy configuration. Any suggestion? Thanks a lot

Hi, I think we need to specify it in the configuration file, right? I have the following configuration motivated from [this](https://github.com/facebookresearch/habitat-api/blob/master/test/test_sensors.py#L438) and it seems like it works as expected:
```
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR']

  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0

  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    NOISE_MODEL: "GaussianNoiseModel"
    NOISE_MODEL_KWARGS:
      INTENSITY_CONSTANT: 0.5

  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    NOISE_MODEL: "RedwoodDepthNoiseModel"

  ACTION_SPACE_CONFIG: "pyrobotnoisy"

  NOISE_MODEL:
    ROBOT: "LoCoBot"
    CONTROLLER: "Proportional"
    NOISE_MULTIPLIER: 0.5
```

**Comment by erikwijmans** [comment]
The keys are what action the planner tells you you should take when forward/left/right/stop is the next best action.  The planner only plans on perfect actions and requires them to be in the action space (it'll find them itself).

You are correct that there is nothing you need to do besides specifying `ACTION_SPACE_CONFIG: "pyrobotnoisy"` .

**Pull request merged**
