### PR TITLE
fix bugs in config setup and pause_env condition

### PR DESCRIPTION
**Pull request by ChanganVR**
## Motivation and Context
* In ppo_trainer.py, environments are paused outside the while loop
* Locally created configs are not used for constructing environments

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by erikwijmans** [comment]
Looks like black isn't happy.  This can be solved with
```
pip install pre-commit
pre-commit install
pre-commit run --all
```

The hooks will trigger on any future commit also.

**Comment by ChanganVR** [comment]
I see. Good to know that. Thanks.

**Comment by mathfac** [comment]
@ChanganVR, thank you for sending the fix. To merge it we need `ci/circleci: python_lint` passing. For this can you run pre-commit hooks that will fix formatting and update the PR:
```
pip install pre-commit
pre-commit install
pre-commit run --all
git commit --amend
git push
```
Thank you!

**Comment by mathfac** [comment]
Looks like I got formatting fixed. Merging.

**Pull request merged**
