### PR TITLE
Made isort for CI check only, shields

### PR DESCRIPTION
**Pull request by mathfac**
## Motivation and Context
Made isort for CI check only.

Shields:
Screenshot 2019-06-14 01 55 24

## How Has This Been Tested
CI shouldn't pass. without fixing `docs/source/conf.py`.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mathfac** [comment]
CI didn't pass as expected: https://circleci.com/gh/facebookresearch/habitat-api/264. Fixing.

**Comment by erikwijmans** [comment]
You'll need to add a `pip install -r requirements.txt` to the setup for the python container as isort needs the python env to know what is an outside package vs. part of HAPI

**Comment by mathfac** [comment]
Issue happening because of pytorch not being in requirements and not installed.

**Comment by mathfac** [comment]
Finally made it work.

**Pull request merged**
