### PR TITLE
Vector env utility functions

### PR DESCRIPTION
**Pull request by danielgordon10**
## Motivation and Context

Extra vector env functions that I found useful for debugging and speeding up eval.

## How Has This Been Tested

Tested extensively during ICCV experiments.

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by abhiskk** [comment]
I think this is not rebased on master, @danielgordon10 can you rebase this? Thanks.

**Comment by danielgordon10** [comment]
It should be now.

**Comment by mathfac** [comment]
@danielgordon10 I like the idea to make VecEnv more general and unlock option to call any function. Can you add tests to make sure we have this functionality working when other code get updated?

**Comment by mathfac** [comment]
Maybe, we can take old test that use `step/reset` actions and run through `call`?

**Comment by danielgordon10** [comment]
I will write some tests for this. It shouldn't be too hard. I'll just add some to the habitat_env tests.

**Comment by danielgordon10** [comment]
I think it's nice to keep the same `step/reset` functions as they align with other environments like gym and even the single Env (not VectorEnv).

**Pull request merged**
